stages:
- build
- release

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY/cmu/ta2eval:live

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build_image:
  stage: build  

  image: docker:stable

  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  before_script:
    - docker info
    - apk update && apk add git
    - cd bayesian_optimization 
    - git fetch
    - git checkout master
    - git merge origin/master
    - cd -
    - git status # should show that your submodule changed

  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:live" -f Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:live"

  only:
    - master

  #uncomment to specify which executor to use
  tags:
    #uncomment to run with docker runner
    - docker
    #uncomment to  run with shell runner
    #- shell

release-image:
  stage: release
  script:
    - docker pull $CI_REGISTRY_IMAGE:live
    - docker tag $CI_REGISTRY_IMAGE:live $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
