stages:
- build
- release

build_image:
  stage: build  

  image: docker:stable

  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  before_script:
    - docker info
    - apk update && apk add git

  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" -f Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:latest"

  only:
    - master

  #uncomment to specify which executor to use
  tags:
    #uncomment to run with docker runner
    - docker
    #uncomment to  run with shell runner
    #- shell

